const LANGUAGE_BY_EXTENSION: Record<string, string> = {
	astro: "astro",
	bash: "bash",
	c: "c",
	cfg: "ini",
	cpp: "cpp",
	cs: "csharp",
	css: "css",
	dart: "dart",
	env: "ini",
	gitignore: "plaintext",
	go: "go",
	graphql: "graphql",
	h: "c",
	hpp: "cpp",
	html: "html",
	java: "java",
	js: "javascript",
	json: "json",
	jsx: "jsx",
	kt: "kotlin",
	less: "less",
	lock: "plaintext",
	md: "markdown",
	php: "php",
	py: "python",
	r: "r",
	rb: "ruby",
	rs: "rust",
	scss: "scss",
	sh: "bash",
	snap: "plaintext",
	sql: "sql",
	svelte: "svelte",
	swift: "swift",
	toml: "ini",
	ts: "typescript",
	tsx: "tsx",
	vue: "vue",
	xml: "xml",
	yaml: "yaml",
	yml: "yaml",
	zsh: "bash",
};

export function detectLanguage(filename: string): string {
	const extension = filename.split(".").pop()?.toLowerCase() ?? "";
	return LANGUAGE_BY_EXTENSION[extension] ?? "plaintext";
}
