/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as SettingsGitTokensRouteImport } from './routes/settings.git-tokens'
import { Route as OrganizationsOrganizationIndexRouteImport } from './routes/organizations.$organization.index'
import { Route as ApiV1OrganizationsRouteImport } from './routes/api/v1/organizations'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiGitSplatRouteImport } from './routes/api/git/$'
import { Route as OrganizationsOrganizationRepositoriesRepositoryRouteImport } from './routes/organizations.$organization.repositories.$repository'
import { Route as ApiV1OrganizationsOrganizationRouteImport } from './routes/api/v1/organizations.$organization'
import { Route as ApiV1AuthRegisterRouteImport } from './routes/api/v1/auth.register'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth.me'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth.logout'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth.login'
import { Route as ApiV1AuthGitTokensRouteImport } from './routes/api/v1/auth.git-tokens'
import { Route as OrganizationsOrganizationRepositoriesRepositoryIndexRouteImport } from './routes/organizations.$organization.repositories.$repository.index'
import { Route as OrganizationsOrganizationRepositoriesRepositorySettingsRouteImport } from './routes/organizations.$organization.repositories.$repository.settings'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRouteImport } from './routes/api/v1/organizations.$organization.repositories'
import { Route as ApiV1OrganizationsOrganizationMembersRouteImport } from './routes/api/v1/organizations.$organization.members'
import { Route as ApiV1AuthGitTokensTokenIdRouteImport } from './routes/api/v1/auth.git-tokens.$tokenId'
import { Route as OrganizationsOrganizationRepositoriesRepositoryPullsIndexRouteImport } from './routes/organizations.$organization.repositories.$repository.pulls.index'
import { Route as OrganizationsOrganizationRepositoriesRepositoryPullsNewRouteImport } from './routes/organizations.$organization.repositories.$repository.pulls.new'
import { Route as OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteImport } from './routes/organizations.$organization.repositories.$repository.pulls.$pullId'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteImport } from './routes/api/v1/organizations.$organization.repositories.$repository'
import { Route as ApiV1OrganizationsOrganizationMembersUserIdRouteImport } from './routes/api/v1/organizations.$organization.members.$userId'
import { Route as OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRouteImport } from './routes/organizations.$organization.repositories.$repository.tree.$branch.index'
import { Route as OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRouteImport } from './routes/organizations.$organization.repositories.$repository.pulls.$pullId.index'
import { Route as OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteImport } from './routes/organizations.$organization.repositories.$repository.tree.$branch.commits'
import { Route as OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRouteImport } from './routes/organizations.$organization.repositories.$repository.tree.$branch.$'
import { Route as OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRouteImport } from './routes/organizations.$organization.repositories.$repository.pulls.$pullId.files'
import { Route as OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRouteImport } from './routes/organizations.$organization.repositories.$repository.blob.$branch.$'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteImport } from './routes/api/v1/organizations.$organization.repositories.$repository.pull-requests'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteImport } from './routes/api/v1/organizations.$organization.repositories.$repository.members'
import { Route as OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRouteImport } from './routes/organizations.$organization.repositories.$repository.tree.$branch.commits.index'
import { Route as OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRouteImport } from './routes/organizations.$organization.repositories.$repository.tree.$branch.commits.$sha'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteImport } from './routes/api/v1/organizations.$organization.repositories.$repository.pull-requests.$pullId'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRouteImport } from './routes/api/v1/organizations.$organization.repositories.$repository.members.$userId'
import { Route as ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRouteImport } from './routes/api/v1/organizations.$organization.repositories.$repository.pull-requests.$pullId.merge'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const SettingsGitTokensRoute = SettingsGitTokensRouteImport.update({
  id: '/git-tokens',
  path: '/git-tokens',
  getParentRoute: () => SettingsRoute,
} as any)
const OrganizationsOrganizationIndexRoute =
  OrganizationsOrganizationIndexRouteImport.update({
    id: '/$organization/',
    path: '/$organization/',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const ApiV1OrganizationsRoute = ApiV1OrganizationsRouteImport.update({
  id: '/api/v1/organizations',
  path: '/api/v1/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitSplatRoute = ApiGitSplatRouteImport.update({
  id: '/api/git/$',
  path: '/api/git/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationRepositoriesRepositoryRoute =
  OrganizationsOrganizationRepositoriesRepositoryRouteImport.update({
    id: '/$organization/repositories/$repository',
    path: '/$organization/repositories/$repository',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const ApiV1OrganizationsOrganizationRoute =
  ApiV1OrganizationsOrganizationRouteImport.update({
    id: '/$organization',
    path: '/$organization',
    getParentRoute: () => ApiV1OrganizationsRoute,
  } as any)
const ApiV1AuthRegisterRoute = ApiV1AuthRegisterRouteImport.update({
  id: '/api/v1/auth/register',
  path: '/api/v1/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthGitTokensRoute = ApiV1AuthGitTokensRouteImport.update({
  id: '/api/v1/auth/git-tokens',
  path: '/api/v1/auth/git-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationRepositoriesRepositoryIndexRoute =
  OrganizationsOrganizationRepositoriesRepositoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationRepositoriesRepositoryRoute,
  } as any)
const OrganizationsOrganizationRepositoriesRepositorySettingsRoute =
  OrganizationsOrganizationRepositoriesRepositorySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationsOrganizationRepositoriesRepositoryRoute,
  } as any)
const ApiV1OrganizationsOrganizationRepositoriesRoute =
  ApiV1OrganizationsOrganizationRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => ApiV1OrganizationsOrganizationRoute,
  } as any)
const ApiV1OrganizationsOrganizationMembersRoute =
  ApiV1OrganizationsOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ApiV1OrganizationsOrganizationRoute,
  } as any)
const ApiV1AuthGitTokensTokenIdRoute =
  ApiV1AuthGitTokensTokenIdRouteImport.update({
    id: '/$tokenId',
    path: '/$tokenId',
    getParentRoute: () => ApiV1AuthGitTokensRoute,
  } as any)
const OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute =
  OrganizationsOrganizationRepositoriesRepositoryPullsIndexRouteImport.update({
    id: '/pulls/',
    path: '/pulls/',
    getParentRoute: () => OrganizationsOrganizationRepositoriesRepositoryRoute,
  } as any)
const OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute =
  OrganizationsOrganizationRepositoriesRepositoryPullsNewRouteImport.update({
    id: '/pulls/new',
    path: '/pulls/new',
    getParentRoute: () => OrganizationsOrganizationRepositoriesRepositoryRoute,
  } as any)
const OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute =
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteImport.update({
    id: '/pulls/$pullId',
    path: '/pulls/$pullId',
    getParentRoute: () => OrganizationsOrganizationRepositoriesRepositoryRoute,
  } as any)
const ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteImport.update({
    id: '/$repository',
    path: '/$repository',
    getParentRoute: () => ApiV1OrganizationsOrganizationRepositoriesRoute,
  } as any)
const ApiV1OrganizationsOrganizationMembersUserIdRoute =
  ApiV1OrganizationsOrganizationMembersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiV1OrganizationsOrganizationMembersRoute,
  } as any)
const OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute =
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRouteImport.update(
    {
      id: '/tree/$branch/',
      path: '/tree/$branch/',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute =
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute =
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteImport.update(
    {
      id: '/tree/$branch/commits',
      path: '/tree/$branch/commits',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute =
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRouteImport.update(
    {
      id: '/tree/$branch/$',
      path: '/tree/$branch/$',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute =
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRouteImport.update(
    {
      id: '/files',
      path: '/files',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute =
  OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRouteImport.update(
    {
      id: '/blob/$branch/$',
      path: '/blob/$branch/$',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRoute =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteImport.update(
    {
      id: '/pull-requests',
      path: '/pull-requests',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRoute =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteImport.update(
    {
      id: '/members',
      path: '/members',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute =
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute,
    } as any,
  )
const OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute =
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRouteImport.update(
    {
      id: '/$sha',
      path: '/$sha',
      getParentRoute: () =>
        OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRoute =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteImport.update(
    {
      id: '/$pullId',
      path: '/$pullId',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRouteImport.update(
    {
      id: '/$userId',
      path: '/$userId',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRouteImport.update(
    {
      id: '/merge',
      path: '/merge',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/git-tokens': typeof SettingsGitTokensRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/organizations': typeof ApiV1OrganizationsRouteWithChildren
  '/organizations/$organization/': typeof OrganizationsOrganizationIndexRoute
  '/api/v1/auth/git-tokens': typeof ApiV1AuthGitTokensRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/organizations/$organization': typeof ApiV1OrganizationsOrganizationRouteWithChildren
  '/organizations/$organization/repositories/$repository': typeof OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
  '/api/v1/auth/git-tokens/$tokenId': typeof ApiV1AuthGitTokensTokenIdRoute
  '/api/v1/organizations/$organization/members': typeof ApiV1OrganizationsOrganizationMembersRouteWithChildren
  '/api/v1/organizations/$organization/repositories': typeof ApiV1OrganizationsOrganizationRepositoriesRouteWithChildren
  '/organizations/$organization/repositories/$repository/settings': typeof OrganizationsOrganizationRepositoriesRepositorySettingsRoute
  '/organizations/$organization/repositories/$repository/': typeof OrganizationsOrganizationRepositoriesRepositoryIndexRoute
  '/api/v1/organizations/$organization/members/$userId': typeof ApiV1OrganizationsOrganizationMembersUserIdRoute
  '/api/v1/organizations/$organization/repositories/$repository': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/$pullId': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/new': typeof OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute
  '/organizations/$organization/repositories/$repository/pulls/': typeof OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/members': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteWithChildren
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteWithChildren
  '/organizations/$organization/repositories/$repository/blob/$branch/$': typeof OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute
  '/organizations/$organization/repositories/$repository/pulls/$pullId/files': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/$': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/commits': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/$pullId/': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/members/$userId': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteWithChildren
  '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/commits/': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings/git-tokens': typeof SettingsGitTokensRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/organizations': typeof ApiV1OrganizationsRouteWithChildren
  '/organizations/$organization': typeof OrganizationsOrganizationIndexRoute
  '/api/v1/auth/git-tokens': typeof ApiV1AuthGitTokensRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/organizations/$organization': typeof ApiV1OrganizationsOrganizationRouteWithChildren
  '/api/v1/auth/git-tokens/$tokenId': typeof ApiV1AuthGitTokensTokenIdRoute
  '/api/v1/organizations/$organization/members': typeof ApiV1OrganizationsOrganizationMembersRouteWithChildren
  '/api/v1/organizations/$organization/repositories': typeof ApiV1OrganizationsOrganizationRepositoriesRouteWithChildren
  '/organizations/$organization/repositories/$repository/settings': typeof OrganizationsOrganizationRepositoriesRepositorySettingsRoute
  '/organizations/$organization/repositories/$repository': typeof OrganizationsOrganizationRepositoriesRepositoryIndexRoute
  '/api/v1/organizations/$organization/members/$userId': typeof ApiV1OrganizationsOrganizationMembersUserIdRoute
  '/api/v1/organizations/$organization/repositories/$repository': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/new': typeof OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute
  '/organizations/$organization/repositories/$repository/pulls': typeof OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/members': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteWithChildren
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteWithChildren
  '/organizations/$organization/repositories/$repository/blob/$branch/$': typeof OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute
  '/organizations/$organization/repositories/$repository/pulls/$pullId/files': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/$': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute
  '/organizations/$organization/repositories/$repository/pulls/$pullId': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute
  '/organizations/$organization/repositories/$repository/tree/$branch': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/members/$userId': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteWithChildren
  '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/commits': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/git-tokens': typeof SettingsGitTokensRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/organizations': typeof ApiV1OrganizationsRouteWithChildren
  '/organizations/$organization/': typeof OrganizationsOrganizationIndexRoute
  '/api/v1/auth/git-tokens': typeof ApiV1AuthGitTokensRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/organizations/$organization': typeof ApiV1OrganizationsOrganizationRouteWithChildren
  '/organizations/$organization/repositories/$repository': typeof OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
  '/api/v1/auth/git-tokens/$tokenId': typeof ApiV1AuthGitTokensTokenIdRoute
  '/api/v1/organizations/$organization/members': typeof ApiV1OrganizationsOrganizationMembersRouteWithChildren
  '/api/v1/organizations/$organization/repositories': typeof ApiV1OrganizationsOrganizationRepositoriesRouteWithChildren
  '/organizations/$organization/repositories/$repository/settings': typeof OrganizationsOrganizationRepositoriesRepositorySettingsRoute
  '/organizations/$organization/repositories/$repository/': typeof OrganizationsOrganizationRepositoriesRepositoryIndexRoute
  '/api/v1/organizations/$organization/members/$userId': typeof ApiV1OrganizationsOrganizationMembersUserIdRoute
  '/api/v1/organizations/$organization/repositories/$repository': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/$pullId': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/new': typeof OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute
  '/organizations/$organization/repositories/$repository/pulls/': typeof OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/members': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteWithChildren
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteWithChildren
  '/organizations/$organization/repositories/$repository/blob/$branch/$': typeof OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute
  '/organizations/$organization/repositories/$repository/pulls/$pullId/files': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/$': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/commits': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteWithChildren
  '/organizations/$organization/repositories/$repository/pulls/$pullId/': typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/members/$userId': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteWithChildren
  '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute
  '/organizations/$organization/repositories/$repository/tree/$branch/commits/': typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute
  '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge': typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/organizations'
    | '/settings'
    | '/settings/git-tokens'
    | '/organizations/'
    | '/settings/'
    | '/api/git/$'
    | '/api/v1/openapi.json'
    | '/api/v1/organizations'
    | '/organizations/$organization/'
    | '/api/v1/auth/git-tokens'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/register'
    | '/api/v1/organizations/$organization'
    | '/organizations/$organization/repositories/$repository'
    | '/api/v1/auth/git-tokens/$tokenId'
    | '/api/v1/organizations/$organization/members'
    | '/api/v1/organizations/$organization/repositories'
    | '/organizations/$organization/repositories/$repository/settings'
    | '/organizations/$organization/repositories/$repository/'
    | '/api/v1/organizations/$organization/members/$userId'
    | '/api/v1/organizations/$organization/repositories/$repository'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId'
    | '/organizations/$organization/repositories/$repository/pulls/new'
    | '/organizations/$organization/repositories/$repository/pulls/'
    | '/api/v1/organizations/$organization/repositories/$repository/members'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests'
    | '/organizations/$organization/repositories/$repository/blob/$branch/$'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId/files'
    | '/organizations/$organization/repositories/$repository/tree/$branch/$'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId/'
    | '/organizations/$organization/repositories/$repository/tree/$branch/'
    | '/api/v1/organizations/$organization/repositories/$repository/members/$userId'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits/'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings/git-tokens'
    | '/organizations'
    | '/settings'
    | '/api/git/$'
    | '/api/v1/openapi.json'
    | '/api/v1/organizations'
    | '/organizations/$organization'
    | '/api/v1/auth/git-tokens'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/register'
    | '/api/v1/organizations/$organization'
    | '/api/v1/auth/git-tokens/$tokenId'
    | '/api/v1/organizations/$organization/members'
    | '/api/v1/organizations/$organization/repositories'
    | '/organizations/$organization/repositories/$repository/settings'
    | '/organizations/$organization/repositories/$repository'
    | '/api/v1/organizations/$organization/members/$userId'
    | '/api/v1/organizations/$organization/repositories/$repository'
    | '/organizations/$organization/repositories/$repository/pulls/new'
    | '/organizations/$organization/repositories/$repository/pulls'
    | '/api/v1/organizations/$organization/repositories/$repository/members'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests'
    | '/organizations/$organization/repositories/$repository/blob/$branch/$'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId/files'
    | '/organizations/$organization/repositories/$repository/tree/$branch/$'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId'
    | '/organizations/$organization/repositories/$repository/tree/$branch'
    | '/api/v1/organizations/$organization/repositories/$repository/members/$userId'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/organizations'
    | '/settings'
    | '/settings/git-tokens'
    | '/organizations/'
    | '/settings/'
    | '/api/git/$'
    | '/api/v1/openapi.json'
    | '/api/v1/organizations'
    | '/organizations/$organization/'
    | '/api/v1/auth/git-tokens'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/register'
    | '/api/v1/organizations/$organization'
    | '/organizations/$organization/repositories/$repository'
    | '/api/v1/auth/git-tokens/$tokenId'
    | '/api/v1/organizations/$organization/members'
    | '/api/v1/organizations/$organization/repositories'
    | '/organizations/$organization/repositories/$repository/settings'
    | '/organizations/$organization/repositories/$repository/'
    | '/api/v1/organizations/$organization/members/$userId'
    | '/api/v1/organizations/$organization/repositories/$repository'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId'
    | '/organizations/$organization/repositories/$repository/pulls/new'
    | '/organizations/$organization/repositories/$repository/pulls/'
    | '/api/v1/organizations/$organization/repositories/$repository/members'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests'
    | '/organizations/$organization/repositories/$repository/blob/$branch/$'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId/files'
    | '/organizations/$organization/repositories/$repository/tree/$branch/$'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits'
    | '/organizations/$organization/repositories/$repository/pulls/$pullId/'
    | '/organizations/$organization/repositories/$repository/tree/$branch/'
    | '/api/v1/organizations/$organization/repositories/$repository/members/$userId'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha'
    | '/organizations/$organization/repositories/$repository/tree/$branch/commits/'
    | '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiGitSplatRoute: typeof ApiGitSplatRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1OrganizationsRoute: typeof ApiV1OrganizationsRouteWithChildren
  ApiV1AuthGitTokensRoute: typeof ApiV1AuthGitTokensRouteWithChildren
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1AuthRegisterRoute: typeof ApiV1AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/settings/git-tokens': {
      id: '/settings/git-tokens'
      path: '/git-tokens'
      fullPath: '/settings/git-tokens'
      preLoaderRoute: typeof SettingsGitTokensRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/organizations/$organization/': {
      id: '/organizations/$organization/'
      path: '/$organization'
      fullPath: '/organizations/$organization/'
      preLoaderRoute: typeof OrganizationsOrganizationIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/api/v1/organizations': {
      id: '/api/v1/organizations'
      path: '/api/v1/organizations'
      fullPath: '/api/v1/organizations'
      preLoaderRoute: typeof ApiV1OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git/$': {
      id: '/api/git/$'
      path: '/api/git/$'
      fullPath: '/api/git/$'
      preLoaderRoute: typeof ApiGitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organization/repositories/$repository': {
      id: '/organizations/$organization/repositories/$repository'
      path: '/$organization/repositories/$repository'
      fullPath: '/organizations/$organization/repositories/$repository'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/api/v1/organizations/$organization': {
      id: '/api/v1/organizations/$organization'
      path: '/$organization'
      fullPath: '/api/v1/organizations/$organization'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRouteImport
      parentRoute: typeof ApiV1OrganizationsRoute
    }
    '/api/v1/auth/register': {
      id: '/api/v1/auth/register'
      path: '/api/v1/auth/register'
      fullPath: '/api/v1/auth/register'
      preLoaderRoute: typeof ApiV1AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/git-tokens': {
      id: '/api/v1/auth/git-tokens'
      path: '/api/v1/auth/git-tokens'
      fullPath: '/api/v1/auth/git-tokens'
      preLoaderRoute: typeof ApiV1AuthGitTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organization/repositories/$repository/': {
      id: '/organizations/$organization/repositories/$repository/'
      path: '/'
      fullPath: '/organizations/$organization/repositories/$repository/'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/settings': {
      id: '/organizations/$organization/repositories/$repository/settings'
      path: '/settings'
      fullPath: '/organizations/$organization/repositories/$repository/settings'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositorySettingsRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/api/v1/organizations/$organization/repositories': {
      id: '/api/v1/organizations/$organization/repositories'
      path: '/repositories'
      fullPath: '/api/v1/organizations/$organization/repositories'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRoute
    }
    '/api/v1/organizations/$organization/members': {
      id: '/api/v1/organizations/$organization/members'
      path: '/members'
      fullPath: '/api/v1/organizations/$organization/members'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationMembersRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRoute
    }
    '/api/v1/auth/git-tokens/$tokenId': {
      id: '/api/v1/auth/git-tokens/$tokenId'
      path: '/$tokenId'
      fullPath: '/api/v1/auth/git-tokens/$tokenId'
      preLoaderRoute: typeof ApiV1AuthGitTokensTokenIdRouteImport
      parentRoute: typeof ApiV1AuthGitTokensRoute
    }
    '/organizations/$organization/repositories/$repository/pulls/': {
      id: '/organizations/$organization/repositories/$repository/pulls/'
      path: '/pulls'
      fullPath: '/organizations/$organization/repositories/$repository/pulls/'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/pulls/new': {
      id: '/organizations/$organization/repositories/$repository/pulls/new'
      path: '/pulls/new'
      fullPath: '/organizations/$organization/repositories/$repository/pulls/new'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsNewRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/pulls/$pullId': {
      id: '/organizations/$organization/repositories/$repository/pulls/$pullId'
      path: '/pulls/$pullId'
      fullPath: '/organizations/$organization/repositories/$repository/pulls/$pullId'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/api/v1/organizations/$organization/repositories/$repository': {
      id: '/api/v1/organizations/$organization/repositories/$repository'
      path: '/$repository'
      fullPath: '/api/v1/organizations/$organization/repositories/$repository'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRoute
    }
    '/api/v1/organizations/$organization/members/$userId': {
      id: '/api/v1/organizations/$organization/members/$userId'
      path: '/$userId'
      fullPath: '/api/v1/organizations/$organization/members/$userId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationMembersUserIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationMembersRoute
    }
    '/organizations/$organization/repositories/$repository/tree/$branch/': {
      id: '/organizations/$organization/repositories/$repository/tree/$branch/'
      path: '/tree/$branch'
      fullPath: '/organizations/$organization/repositories/$repository/tree/$branch/'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/pulls/$pullId/': {
      id: '/organizations/$organization/repositories/$repository/pulls/$pullId/'
      path: '/'
      fullPath: '/organizations/$organization/repositories/$repository/pulls/$pullId/'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute
    }
    '/organizations/$organization/repositories/$repository/tree/$branch/commits': {
      id: '/organizations/$organization/repositories/$repository/tree/$branch/commits'
      path: '/tree/$branch/commits'
      fullPath: '/organizations/$organization/repositories/$repository/tree/$branch/commits'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/tree/$branch/$': {
      id: '/organizations/$organization/repositories/$repository/tree/$branch/$'
      path: '/tree/$branch/$'
      fullPath: '/organizations/$organization/repositories/$repository/tree/$branch/$'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/pulls/$pullId/files': {
      id: '/organizations/$organization/repositories/$repository/pulls/$pullId/files'
      path: '/files'
      fullPath: '/organizations/$organization/repositories/$repository/pulls/$pullId/files'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute
    }
    '/organizations/$organization/repositories/$repository/blob/$branch/$': {
      id: '/organizations/$organization/repositories/$repository/blob/$branch/$'
      path: '/blob/$branch/$'
      fullPath: '/organizations/$organization/repositories/$repository/blob/$branch/$'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/api/v1/organizations/$organization/repositories/$repository/pull-requests': {
      id: '/api/v1/organizations/$organization/repositories/$repository/pull-requests'
      path: '/pull-requests'
      fullPath: '/api/v1/organizations/$organization/repositories/$repository/pull-requests'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/api/v1/organizations/$organization/repositories/$repository/members': {
      id: '/api/v1/organizations/$organization/repositories/$repository/members'
      path: '/members'
      fullPath: '/api/v1/organizations/$organization/repositories/$repository/members'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute
    }
    '/organizations/$organization/repositories/$repository/tree/$branch/commits/': {
      id: '/organizations/$organization/repositories/$repository/tree/$branch/commits/'
      path: '/'
      fullPath: '/organizations/$organization/repositories/$repository/tree/$branch/commits/'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute
    }
    '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha': {
      id: '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha'
      path: '/$sha'
      fullPath: '/organizations/$organization/repositories/$repository/tree/$branch/commits/$sha'
      preLoaderRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRouteImport
      parentRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute
    }
    '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId': {
      id: '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId'
      path: '/$pullId'
      fullPath: '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRoute
    }
    '/api/v1/organizations/$organization/repositories/$repository/members/$userId': {
      id: '/api/v1/organizations/$organization/repositories/$repository/members/$userId'
      path: '/$userId'
      fullPath: '/api/v1/organizations/$organization/repositories/$repository/members/$userId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRoute
    }
    '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge': {
      id: '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge'
      path: '/merge'
      fullPath: '/api/v1/organizations/$organization/repositories/$repository/pull-requests/$pullId/merge'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRoute
    }
  }
}

interface OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteChildren {
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute
}

const OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteChildren: OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteChildren =
  {
    OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute:
      OrganizationsOrganizationRepositoriesRepositoryPullsPullIdFilesRoute,
    OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute:
      OrganizationsOrganizationRepositoriesRepositoryPullsPullIdIndexRoute,
  }

const OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteWithChildren =
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute._addFileChildren(
    OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteChildren,
  )

interface OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteChildren {
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute
}

const OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteChildren: OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteChildren =
  {
    OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute:
      OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsShaRoute,
    OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute:
      OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsIndexRoute,
  }

const OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteWithChildren =
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute._addFileChildren(
    OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteChildren,
  )

interface OrganizationsOrganizationRepositoriesRepositoryRouteChildren {
  OrganizationsOrganizationRepositoriesRepositorySettingsRoute: typeof OrganizationsOrganizationRepositoriesRepositorySettingsRoute
  OrganizationsOrganizationRepositoriesRepositoryIndexRoute: typeof OrganizationsOrganizationRepositoriesRepositoryIndexRoute
  OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteWithChildren
  OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute
  OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute: typeof OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute
  OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute: typeof OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteWithChildren
  OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute: typeof OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute
}

const OrganizationsOrganizationRepositoriesRepositoryRouteChildren: OrganizationsOrganizationRepositoriesRepositoryRouteChildren =
  {
    OrganizationsOrganizationRepositoriesRepositorySettingsRoute:
      OrganizationsOrganizationRepositoriesRepositorySettingsRoute,
    OrganizationsOrganizationRepositoriesRepositoryIndexRoute:
      OrganizationsOrganizationRepositoriesRepositoryIndexRoute,
    OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRoute:
      OrganizationsOrganizationRepositoriesRepositoryPullsPullIdRouteWithChildren,
    OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute:
      OrganizationsOrganizationRepositoriesRepositoryPullsNewRoute,
    OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute:
      OrganizationsOrganizationRepositoriesRepositoryPullsIndexRoute,
    OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute:
      OrganizationsOrganizationRepositoriesRepositoryBlobBranchSplatRoute,
    OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute:
      OrganizationsOrganizationRepositoriesRepositoryTreeBranchSplatRoute,
    OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRoute:
      OrganizationsOrganizationRepositoriesRepositoryTreeBranchCommitsRouteWithChildren,
    OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute:
      OrganizationsOrganizationRepositoriesRepositoryTreeBranchIndexRoute,
  }

const OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren =
  OrganizationsOrganizationRepositoriesRepositoryRoute._addFileChildren(
    OrganizationsOrganizationRepositoriesRepositoryRouteChildren,
  )

interface OrganizationsRouteChildren {
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  OrganizationsOrganizationIndexRoute: typeof OrganizationsOrganizationIndexRoute
  OrganizationsOrganizationRepositoriesRepositoryRoute: typeof OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  OrganizationsOrganizationIndexRoute: OrganizationsOrganizationIndexRoute,
  OrganizationsOrganizationRepositoriesRepositoryRoute:
    OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsGitTokensRoute: typeof SettingsGitTokensRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsGitTokensRoute: SettingsGitTokensRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiV1OrganizationsOrganizationMembersRouteChildren {
  ApiV1OrganizationsOrganizationMembersUserIdRoute: typeof ApiV1OrganizationsOrganizationMembersUserIdRoute
}

const ApiV1OrganizationsOrganizationMembersRouteChildren: ApiV1OrganizationsOrganizationMembersRouteChildren =
  {
    ApiV1OrganizationsOrganizationMembersUserIdRoute:
      ApiV1OrganizationsOrganizationMembersUserIdRoute,
  }

const ApiV1OrganizationsOrganizationMembersRouteWithChildren =
  ApiV1OrganizationsOrganizationMembersRoute._addFileChildren(
    ApiV1OrganizationsOrganizationMembersRouteChildren,
  )

interface ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteChildren {
  ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute
}

const ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteChildren: ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteChildren =
  {
    ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute:
      ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersUserIdRoute,
  }

const ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteWithChildren =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRoute._addFileChildren(
    ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteChildren,
  )

interface ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteChildren {
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute
}

const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteChildren: ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteChildren =
  {
    ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute:
      ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdMergeRoute,
  }

const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteWithChildren =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRoute._addFileChildren(
    ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteChildren,
  )

interface ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteChildren {
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteWithChildren
}

const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteChildren: ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteChildren =
  {
    ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRoute:
      ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsPullIdRouteWithChildren,
  }

const ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteWithChildren =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRoute._addFileChildren(
    ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteChildren,
  )

interface ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteChildren {
  ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteWithChildren
  ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteWithChildren
}

const ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteChildren: ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteChildren =
  {
    ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRoute:
      ApiV1OrganizationsOrganizationRepositoriesRepositoryMembersRouteWithChildren,
    ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRoute:
      ApiV1OrganizationsOrganizationRepositoriesRepositoryPullRequestsRouteWithChildren,
  }

const ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren =
  ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute._addFileChildren(
    ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteChildren,
  )

interface ApiV1OrganizationsOrganizationRepositoriesRouteChildren {
  ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren
}

const ApiV1OrganizationsOrganizationRepositoriesRouteChildren: ApiV1OrganizationsOrganizationRepositoriesRouteChildren =
  {
    ApiV1OrganizationsOrganizationRepositoriesRepositoryRoute:
      ApiV1OrganizationsOrganizationRepositoriesRepositoryRouteWithChildren,
  }

const ApiV1OrganizationsOrganizationRepositoriesRouteWithChildren =
  ApiV1OrganizationsOrganizationRepositoriesRoute._addFileChildren(
    ApiV1OrganizationsOrganizationRepositoriesRouteChildren,
  )

interface ApiV1OrganizationsOrganizationRouteChildren {
  ApiV1OrganizationsOrganizationMembersRoute: typeof ApiV1OrganizationsOrganizationMembersRouteWithChildren
  ApiV1OrganizationsOrganizationRepositoriesRoute: typeof ApiV1OrganizationsOrganizationRepositoriesRouteWithChildren
}

const ApiV1OrganizationsOrganizationRouteChildren: ApiV1OrganizationsOrganizationRouteChildren =
  {
    ApiV1OrganizationsOrganizationMembersRoute:
      ApiV1OrganizationsOrganizationMembersRouteWithChildren,
    ApiV1OrganizationsOrganizationRepositoriesRoute:
      ApiV1OrganizationsOrganizationRepositoriesRouteWithChildren,
  }

const ApiV1OrganizationsOrganizationRouteWithChildren =
  ApiV1OrganizationsOrganizationRoute._addFileChildren(
    ApiV1OrganizationsOrganizationRouteChildren,
  )

interface ApiV1OrganizationsRouteChildren {
  ApiV1OrganizationsOrganizationRoute: typeof ApiV1OrganizationsOrganizationRouteWithChildren
}

const ApiV1OrganizationsRouteChildren: ApiV1OrganizationsRouteChildren = {
  ApiV1OrganizationsOrganizationRoute:
    ApiV1OrganizationsOrganizationRouteWithChildren,
}

const ApiV1OrganizationsRouteWithChildren =
  ApiV1OrganizationsRoute._addFileChildren(ApiV1OrganizationsRouteChildren)

interface ApiV1AuthGitTokensRouteChildren {
  ApiV1AuthGitTokensTokenIdRoute: typeof ApiV1AuthGitTokensTokenIdRoute
}

const ApiV1AuthGitTokensRouteChildren: ApiV1AuthGitTokensRouteChildren = {
  ApiV1AuthGitTokensTokenIdRoute: ApiV1AuthGitTokensTokenIdRoute,
}

const ApiV1AuthGitTokensRouteWithChildren =
  ApiV1AuthGitTokensRoute._addFileChildren(ApiV1AuthGitTokensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ApiGitSplatRoute: ApiGitSplatRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1OrganizationsRoute: ApiV1OrganizationsRouteWithChildren,
  ApiV1AuthGitTokensRoute: ApiV1AuthGitTokensRouteWithChildren,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1AuthRegisterRoute: ApiV1AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
