/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as RepositoriesNameRouteImport } from './routes/repositories.$name'
import { Route as RepositoriesNameIndexRouteImport } from './routes/repositories.$name.index'
import { Route as ApiGitSplatRouteImport } from './routes/api/git/$'
import { Route as RepositoriesNameTreeBranchIndexRouteImport } from './routes/repositories.$name.tree.$branch.index'
import { Route as RepositoriesNameTreeBranchCommitsRouteImport } from './routes/repositories.$name.tree.$branch.commits'
import { Route as RepositoriesNameTreeBranchSplatRouteImport } from './routes/repositories.$name.tree.$branch.$'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesNameRoute = RepositoriesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesNameIndexRoute = RepositoriesNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesNameRoute,
} as any)
const ApiGitSplatRoute = ApiGitSplatRouteImport.update({
  id: '/api/git/$',
  path: '/api/git/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesNameTreeBranchIndexRoute =
  RepositoriesNameTreeBranchIndexRouteImport.update({
    id: '/tree/$branch/',
    path: '/tree/$branch/',
    getParentRoute: () => RepositoriesNameRoute,
  } as any)
const RepositoriesNameTreeBranchCommitsRoute =
  RepositoriesNameTreeBranchCommitsRouteImport.update({
    id: '/tree/$branch/commits',
    path: '/tree/$branch/commits',
    getParentRoute: () => RepositoriesNameRoute,
  } as any)
const RepositoriesNameTreeBranchSplatRoute =
  RepositoriesNameTreeBranchSplatRouteImport.update({
    id: '/tree/$branch/$',
    path: '/tree/$branch/$',
    getParentRoute: () => RepositoriesNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/$name': typeof RepositoriesNameRouteWithChildren
  '/repositories/': typeof RepositoriesIndexRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/repositories/$name/': typeof RepositoriesNameIndexRoute
  '/repositories/$name/tree/$branch/$': typeof RepositoriesNameTreeBranchSplatRoute
  '/repositories/$name/tree/$branch/commits': typeof RepositoriesNameTreeBranchCommitsRoute
  '/repositories/$name/tree/$branch/': typeof RepositoriesNameTreeBranchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/repositories/$name': typeof RepositoriesNameIndexRoute
  '/repositories/$name/tree/$branch/$': typeof RepositoriesNameTreeBranchSplatRoute
  '/repositories/$name/tree/$branch/commits': typeof RepositoriesNameTreeBranchCommitsRoute
  '/repositories/$name/tree/$branch': typeof RepositoriesNameTreeBranchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/$name': typeof RepositoriesNameRouteWithChildren
  '/repositories/': typeof RepositoriesIndexRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/repositories/$name/': typeof RepositoriesNameIndexRoute
  '/repositories/$name/tree/$branch/$': typeof RepositoriesNameTreeBranchSplatRoute
  '/repositories/$name/tree/$branch/commits': typeof RepositoriesNameTreeBranchCommitsRoute
  '/repositories/$name/tree/$branch/': typeof RepositoriesNameTreeBranchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repositories'
    | '/repositories/$name'
    | '/repositories/'
    | '/api/git/$'
    | '/repositories/$name/'
    | '/repositories/$name/tree/$branch/$'
    | '/repositories/$name/tree/$branch/commits'
    | '/repositories/$name/tree/$branch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/repositories'
    | '/api/git/$'
    | '/repositories/$name'
    | '/repositories/$name/tree/$branch/$'
    | '/repositories/$name/tree/$branch/commits'
    | '/repositories/$name/tree/$branch'
  id:
    | '__root__'
    | '/'
    | '/repositories'
    | '/repositories/$name'
    | '/repositories/'
    | '/api/git/$'
    | '/repositories/$name/'
    | '/repositories/$name/tree/$branch/$'
    | '/repositories/$name/tree/$branch/commits'
    | '/repositories/$name/tree/$branch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  ApiGitSplatRoute: typeof ApiGitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$name': {
      id: '/repositories/$name'
      path: '/$name'
      fullPath: '/repositories/$name'
      preLoaderRoute: typeof RepositoriesNameRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$name/': {
      id: '/repositories/$name/'
      path: '/'
      fullPath: '/repositories/$name/'
      preLoaderRoute: typeof RepositoriesNameIndexRouteImport
      parentRoute: typeof RepositoriesNameRoute
    }
    '/api/git/$': {
      id: '/api/git/$'
      path: '/api/git/$'
      fullPath: '/api/git/$'
      preLoaderRoute: typeof ApiGitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$name/tree/$branch/': {
      id: '/repositories/$name/tree/$branch/'
      path: '/tree/$branch'
      fullPath: '/repositories/$name/tree/$branch/'
      preLoaderRoute: typeof RepositoriesNameTreeBranchIndexRouteImport
      parentRoute: typeof RepositoriesNameRoute
    }
    '/repositories/$name/tree/$branch/commits': {
      id: '/repositories/$name/tree/$branch/commits'
      path: '/tree/$branch/commits'
      fullPath: '/repositories/$name/tree/$branch/commits'
      preLoaderRoute: typeof RepositoriesNameTreeBranchCommitsRouteImport
      parentRoute: typeof RepositoriesNameRoute
    }
    '/repositories/$name/tree/$branch/$': {
      id: '/repositories/$name/tree/$branch/$'
      path: '/tree/$branch/$'
      fullPath: '/repositories/$name/tree/$branch/$'
      preLoaderRoute: typeof RepositoriesNameTreeBranchSplatRouteImport
      parentRoute: typeof RepositoriesNameRoute
    }
  }
}

interface RepositoriesNameRouteChildren {
  RepositoriesNameIndexRoute: typeof RepositoriesNameIndexRoute
  RepositoriesNameTreeBranchSplatRoute: typeof RepositoriesNameTreeBranchSplatRoute
  RepositoriesNameTreeBranchCommitsRoute: typeof RepositoriesNameTreeBranchCommitsRoute
  RepositoriesNameTreeBranchIndexRoute: typeof RepositoriesNameTreeBranchIndexRoute
}

const RepositoriesNameRouteChildren: RepositoriesNameRouteChildren = {
  RepositoriesNameIndexRoute: RepositoriesNameIndexRoute,
  RepositoriesNameTreeBranchSplatRoute: RepositoriesNameTreeBranchSplatRoute,
  RepositoriesNameTreeBranchCommitsRoute:
    RepositoriesNameTreeBranchCommitsRoute,
  RepositoriesNameTreeBranchIndexRoute: RepositoriesNameTreeBranchIndexRoute,
}

const RepositoriesNameRouteWithChildren =
  RepositoriesNameRoute._addFileChildren(RepositoriesNameRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesNameRoute: typeof RepositoriesNameRouteWithChildren
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesNameRoute: RepositoriesNameRouteWithChildren,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  ApiGitSplatRoute: ApiGitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
